# MySQL Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/alumni_db
spring.datasource.username=root
spring.datasource.password=Parth@3oct

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sidryanite@gmail.com
spring.mail.password=rqpp tftp uxdq vtud
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
